[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "192.168.1.1"
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = false
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = false
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"


bind_dn = "CN=DevOps Ldap,OU=SERVICES,OU=Units,DC=test,DC=local"
bind_password = "1234"

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
# Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
search_filter = "(userPrincipalName=%s)"
#search_filter = "(cn=%s)"

# An array of base dns to search through
#search_base_dns = ["OU=units,DC=test,DC=local"]
search_base_dns = ["DC=test,DC=local"]

#group_search_filter = "((description=%s))"
#group_search_base_dns = ["OU=units,DC=test,DC=local"]
group_search_base_dns = ["DC=test,DC=local"]
#group_search_filter_user_attribute = "description"







[servers.attributes]
name = "givenName"
surname = "sn"
username = "userPrincipalName"
member_of = "department"
email =  "description"


[[servers.group_mappings]]
group_dn = "infrastructure-sre"
org_role = "Admin"
grafana_admin = true


[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"





