global:
  scrape_interval: 1m
  evaluation_interval: 1m

  external_labels:
    cluster: 'My-Prometheus'

###################################################
#### SCRAPE CONFIGS
###################################################
scrape_configs:
###################################################
#### Prometheus
###################################################
- job_name: 'My-prometheus'
  static_configs:
  - targets: ['localhost:9090']

###################################################
#### BlackBox
###################################################

- job_name: 'blackbox-icmp-production'
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [blackbox-icmp]
  file_sd_configs:
  - files:
    - 'tgroups/blackbox-icmp-production.yml'
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115

- job_name: 'blackbox-tcp-production'
  scrape_interval: 1m
  metrics_path: /probe
  params:
    module: [blackbox-tcp]
  file_sd_configs:
  - files:
    - 'tgroups/blackbox-tcp-production.yml'
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115

###################################################
#### Node Exporter
###################################################
- job_name: 'node-exporter-production'
  scrape_interval: 15s
  file_sd_configs:
  - files:
    - 'tgroups/node-exporter-production.yml'

###################################################
#### Thirdparty: Elastic_search
###################################################
- job_name: "thirdparty-elasticsearch"
  file_sd_configs:
  - files:
    - 'tgroups/thirdparty_elasticsearch.yml'

###################################################
#### Thirdparty: Redis
###################################################
- job_name: "thirdparty-redis"
  file_sd_configs:
  - files:
    - 'tgroups/thirdparty_redis.yml'

###################################################
#### Grafana Itself
###################################################
- job_name: grafana
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - grafana:3000
###################################################
#### RabbitMQ
###################################################
- job_name: "thirdparty-rabbitmq"
  scrape_interval: 15s
  metrics_path: /metrics
  file_sd_configs:
  - files:
    - 'tgroups/thirdparty_rabbitmq.yml'

- job_name: "thirdparty-rabbitmq_self"
  scrape_interval: 15s
  metrics_path: /metrics/per-object
  file_sd_configs:
  - files:
    - 'tgroups/thirdparty_rabbitmq_self.yml'

###################################################
#### MinIO
###################################################
- job_name: "thirdparty-minio"
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiV2VHemVlSmwwbks2UVlNbDhHRXEiLCJleHAiOjQ4NTgxNjE4Mjl9.ELgWpA2IzjHIaQx-snsdkEh2_86ijxaaPgxF3IKizDtafs7abMIGpUqKl-mtc-h4gG6KE4Z3NgoHo2S0aPPLYw
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: [minio-api.test.com]

